### ISSUE TITLE
Remove dm after blocking somebody

### ISSUE THREAD

**Issue by mariadaan** [AtibQur/Transcendence#107]
ook na het verwijderen van de vriendschap al de dm chat verwijderen?

**Comment by tessavdvorst** [comment]
**dm**
- [ ] voeg extra check toe in create message -> als de channel een dm is dan mag alleen een friend een bericht sturen.

**groupchannel**
- [ ] fetch messages vervangen met fetch filteredmessages
- [ ] in socket.on('chatmessage') alleen toevoegen aan message als de sender niet geblocked is
