### ISSUE TITLE
Mute for limited time

### ISSUE THREAD

**Issue by mariadaan** [AtibQur/Transcendence#71]
Zullen we dit gewoon op 1 minuut zetten? Dat ze gedurende die minuut niks kunnen sturen

**Comment by tessavdvorst** [comment]
als iemand gemute is dan kunnen channelmembers niks van diegene ontvangen, messages worden ook niet aangemaakt

**Comment by tessavdvorst** [comment]
- [ ] mute functionaliteit via sockets maken
- [ ] muted member op de hoogte hiervan brengen
- [ ] andere channelmembers op de hoogte hiervan maken
- [ ] cronservice aanmaken om mute automatisch na 1 min muted weer te unmuten
- [ ] bij createMessage een check doen of je niet muted bent
- [ ] als het versturen dus niet lukt, toast weergeven dat je gemute bent

**Comment by tessavdvorst** [comment]
als iemand gemute is, kan diegene als ie ook admin is zichzelf unmuten?
